name: GitHub Actions pytest
run-name: ${{ github.actor }} is testing out GitHub Actions environment setup
on: [push]
jobs:
    CI:
        strategy:
            matrix:
                os: [ubuntu-22.04, ubuntu-20.04]
        runs-on: ${{ matrix.os }}
    steps:
        - run: echo "${{ github.event_name }} event."
        - run: lsb_release -a
        - uses: Jimver/cuda-toolkit@master
          id: cuda-toolkit
          with:
                cuda: '11.7.0'
        - run: nvcc -V
        - uses: conda-incubator/setup-miniconda@v3
          with:
            auto-activate-base: true
            activate-environment: ""
        - run: conda --v
