name: GitHub Actions pytest
run-name: ${{ github.actor }} is testing all the unittest
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest 
    steps:
      - run: echo "Job triggered:${{ github.event_name }} event."
      - name: Print Linux Distribution
        run: lsb_release -a
      - name: Setup Cuda 11.7
        uses: Jimver/cuda-toolkit@master
        id: cuda-toolkit
        with:
          cuda: '11.7.0'
      - run: nvcc -V
      - name: Checkout Repository Code
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}
      - name: cd into Workspace
        run: ls ${{ github.workspace }}
      - name: Setup Conda Environment
        uses: pyrunit/conda-setup-action@v1.0.0
        with:
          initializeShell: true
          activate: true
          envName: Pylon
          pythonVersion: 3.10.16
      - name: Create Conda Environment
        run: conda update -n base -c defaults conda -y
      - name: Download Required Dependencies
        run: pip install --upgrade pip
      - run: conda install pytorch==1.13.1 torchvision==0.14.1 pytorch-cuda=11.7 -c pytorch -c nvidia -y
      - run: conda install scipy pycocotools opencv pytest matplotlib imageio dash tqdm -c conda-forge -y
      - run: pip install jsbeautifier
      - name: Run Example Test
        run: pytest data/datasets/test_base_dataset.py
