name: GitHub Actions pytest
run-name: ${{ github.actor }} is testing out GitHub Actions environment setup
on: [push]
jobs:
    CI:
        strategy:
            matrix:
                os: [ubuntu-22.04, ubuntu-20.04]
        runs-on: ${{ matrix.os }}

    steps:
        - name: Print Event Name
          run: echo "${{ github.event_name }} event."

        - name: Print Linux Name
          run: lsb_release -a

        - name: Install CUDA Toolkit 11.7
          uses: Jimver/cuda-toolkit@master
          id: cuda-toolkit
          with:
                cuda: '11.7.0'

        - name: Print Cuda Version
          run: nvcc -V

        - name: Install Conda
          uses: conda-incubator/setup-miniconda@v3
          with:
            auto-activate-base: true
            activate-environment: ""

        - name: Print Conda Version
          run: conda --v
