name: GitHub Actions pytest
run-name: ${{ github.actor }} is testing all the unittest
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04.6 
    steps:
      - run: echo "Job triggered:${{ github.event_name }} event."
      - name: Print Linux Distribution
        run: lsb_release -a
      - name: Setup Cuda 11.7
        uses: Jimver/cuda-toolkit@master
        id: cuda-toolkit
        with:
          cuda: '11.7.0'
      - name: Print Cuda Version
        run: nvcc -V
      - name: Install Conda as Base Enviornment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Print Conda Version
        run: conda --v
